version: "3.9"

services:
  frontend:
    build: ./frontend
    expose:
      - "80"
    depends_on:
      - backend

  backend:
    build: ./backend
    expose:
      - "5050"
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: opsflow
      DB_PORT: 5432
      JWT_SECRET: opsflow_super_secret_key
    depends_on:
      - database

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: opsflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data: